- hosts: all 
  become: true 
  tasks: 
    - name: debug working directory
      debug:
        msg: "{{ ansible_env.PWD }}"
    - name: create new deployment 
      command: sudo kubectl apply -f /home/ec2-user/Deployment.yml
    - name: create new service 
      command: sudo kubectl apply -f /home/ec2-user/Service.yml

